/**
 * Deploys the three ChainMind contracts to the active network, wires them together,
 * and exports ABIs + addresses to /lib/contracts/ for the frontend.
 *
 *   Local:  npm run deploy:local   (after `npm run node` in another terminal)
 *   Monad:  npm run deploy:monad   (needs PRIVATE_KEY in .env, funded with testnet MON)
 *
 * Config via env (optional):
 *   VERIFIER_ADDRESS       backend oracle allowed to assign/complete (default: deployer)
 *   REPUTATION_THRESHOLD   score >= this => trusted/instant settlement (default: 1)
 */
const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

const EXPLORER = "https://testnet.monadexplorer.com";

async function main() {
  const { ethers, network, artifacts } = hre;
  const [deployer] = await ethers.getSigners();

  const verifier = process.env.VERIFIER_ADDRESS || deployer.address;
  const threshold = BigInt(process.env.REPUTATION_THRESHOLD || "1");

  console.log(`\n── Deploying ChainMind to "${network.name}" ──`);
  console.log("Deployer:", deployer.address);
  const bal = await ethers.provider.getBalance(deployer.address);
  console.log("Balance :", ethers.formatEther(bal), "MON");
  if (bal === 0n) {
    throw new Error("Deployer has 0 balance. Fund it from the Monad faucet first.");
  }
  console.log("Verifier:", verifier);
  console.log("Threshold:", threshold.toString(), "\n");

  // 1) ReputationStore (no deps)
  const reputation = await (await ethers.getContractFactory("ReputationStore")).deploy();
  await reputation.waitForDeployment();
  console.log("ReputationStore :", reputation.target);

  // 2) AgentRegistry (no deps)
  const registry = await (await ethers.getContractFactory("AgentRegistry")).deploy();
  await registry.waitForDeployment();
  console.log("AgentRegistry   :", registry.target);

  // 3) TaskMarketplace (depends on the two above)
  const marketplace = await (await ethers.getContractFactory("TaskMarketplace")).deploy(
    registry.target,
    reputation.target,
    verifier,
    threshold
  );
  await marketplace.waitForDeployment();
  console.log("TaskMarketplace :", marketplace.target);

  // 4) Wire: only the marketplace may increment reputation.
  const tx = await reputation.setAuthorizedCaller(marketplace.target);
  await tx.wait();
  console.log("\nWired ReputationStore.authorizedCaller -> TaskMarketplace ✓");

  // 5) Export ABIs + addresses for the frontend.
  await exportArtifacts({
    artifacts,
    chainId: Number(network.config.chainId || (await ethers.provider.getNetwork()).chainId),
    networkName: network.name,
    verifier,
    threshold: threshold.toString(),
    addresses: {
      ReputationStore: reputation.target,
      AgentRegistry: registry.target,
      TaskMarketplace: marketplace.target,
    },
  });

  if (network.name === "monadTestnet") {
    console.log("\nExplorer:");
    console.log(`  ReputationStore : ${EXPLORER}/address/${reputation.target}`);
    console.log(`  AgentRegistry   : ${EXPLORER}/address/${registry.target}`);
    console.log(`  TaskMarketplace : ${EXPLORER}/address/${marketplace.target}`);
  }

  console.log("\n✓ Deploy complete. ABIs + addresses written to /lib/contracts/");
  console.log("  Next: copy these addresses into the frontend .env, then run seed (Phase 6b).\n");
}

async function exportArtifacts({ artifacts, chainId, networkName, verifier, threshold, addresses }) {
  const outDir = path.resolve(__dirname, "../../lib/contracts");
  fs.mkdirSync(outDir, { recursive: true });

  const names = ["ReputationStore", "AgentRegistry", "TaskMarketplace"];
  const abis = {};
  for (const name of names) {
    const art = await artifacts.readArtifact(name);
    abis[name] = art.abi;
    // Per-contract ABI file (handy for direct import).
    fs.writeFileSync(path.join(outDir, `${name}.json`), JSON.stringify(art.abi, null, 2));
  }

  const addressesPayload = { chainId, network: networkName, verifier, reputationThreshold: threshold, ...addresses };
  fs.writeFileSync(path.join(outDir, "addresses.json"), JSON.stringify(addressesPayload, null, 2));

  // TS barrel: single import for the frontend (wagmi/viem-friendly).
  const ts = `// AUTO-GENERATED by contracts/scripts/deploy.js — do not edit by hand.
import ReputationStore from "./ReputationStore.json";
import AgentRegistry from "./AgentRegistry.json";
import TaskMarketplace from "./TaskMarketplace.json";

export const addresses = ${JSON.stringify(addressesPayload, null, 2)} as const;

export const abis = {
  ReputationStore,
  AgentRegistry,
  TaskMarketplace,
} as const;

export const CHAIN = {
  id: ${chainId},
  name: "Monad Testnet",
  rpcUrl: "https://testnet-rpc.monad.xyz",
  explorer: "${EXPLORER}",
  nativeCurrency: { name: "MON", symbol: "MON", decimals: 18 },
} as const;
`;
  fs.writeFileSync(path.join(outDir, "index.ts"), ts);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
